### ISSUE TITLE
Toegankelijkheid van een dataservice is niet eenduidig kardinaliteit 1

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-DCATAPVlaanderen#10]
Dag Bert,
Het modelleren van toegankelijkheid van een dataservice door een eenvoudige property (http://purl.org/dc/terms/accessRights) met kardinaliteit 1 blijft me dwars zitten.
Via onze sparql endpoints en subject pages krijgt een gebruiker toegang tot alle niveau's van dataclassificatie), afhankelijk of een gebruiker al dan niet is aangemeld en van de clearance van die gebruiker. 
Vriendelijke groeten,
Geert

**Comment by bertvannuffelen** [comment]
Dag Geert,

Ik begrijp je uitdaging. 

a) Eerst over waar we de vraag best behandelen:

Ik zie wel dat de vraag in eerste plaats moet opgelost worden in metadata_DCAT applicatieprofiel. Want die keuze is daar gemaakt. Als we het daar niet vrijer maken dan kan het in een specialisatieprofiel niet vrijer gemaakt worden.

Voor DCAT-AP Vlaanderen is het zelfs een restrictie die komt uit DCAT-AP. Dus zolang die niet wijzigt zal het max 1 zijn. En in metadata_DCAT hebben we toen gekozen om hiermee te aligneren.

b) over je vraag zelf:
Je beschrijft hier een situatie waarbij we meerdere perspectieven op elkaar leggen. 
Dat is typisch voor services. Als je een downloadbaar bestand zou maken van de toestand van de dataset in het SPARQL endpoint, dan zou je per doelgroep een bestand maken. En de toegang tot dat bestand regelen.  En dan zou je dus verschillende identificatoren hebben, 1 per bestand voor elke doelgroep. Metadata-gewijs zou dat dan kunnen leiden tot verschillende DCAT entiteiten elk met hun levensloop.

In een service is dat meer dynamisch, je ontrafelt de data niet op basis van toegankelijksheidsparameters. Die informatie is een deel van de data geworden. 
En daardoor kan 1 service endpoint verschillende data perspectieven aanbieden. 

Dus er zijn 2 opties die ik momenteel zie:
    - maak een entiteit per doelgroep verwijzend naar hetzelfde endpointURL
    - geef  aan een entiteit de meest "open" waarde PUBLIC indien de informatie voornamelijk voor het publiek is.

Merk op dat optie 1 misschien vreemd zal overkomen, maar het is zo dat het endpointURL niet de identificator is voor de data service. Dus je kan dus de overlap van perspectieven ook weergeven als verschillende metadata beschrijvingen verwijzend naar hetzelfde endpointURL.

Optie 2 is momenteel de suggestie die voor geodata en open data wordt gedaan. Maar als de balans misschien erg gelijklopend is, dan is optie 1 zeker te bekijken.

Zouden deze 2 opties je al verder helpen? Of moeten we volgens jou het pad verder onderzoeken naar het verwijderen van de max-cardinaliteits optie? Dat zal zeker ook interactie met de internationale profielen vereisen.

**Comment by gezever** [comment]
Dank je wel voor het uitgebreide anwoord Bert.
Optie 1, meerdere dataservices op hetzelfde endpoint, is het meest expliciet.  We gaan dit zo implementeren.
Vriendelijke groeten,
Geert
